################################################################
## Conda environment for analysis of SARS-CoV-2 sequences
name: covid-19

channels:
  - bioconda
  - conda-forge
  - r

dependencies:

  ## Command-line tools
  - tpeulen::pymol-open-source  # structure analysis and visualisation. Note: the conda package does not work on Mac OS X, but the tool can be installed with brew
  - bioconda::clustalw  # Multiple alignment of nucleic acid and protein sequences
  - bioconda::muscle    # MUSCLE: multiple sequence alignment with high accuracy and high throughput
  - bioconda::mafft     # Multiple alignment program for amino acid or nucleotide sequences based on fast Fourier transform
  - bioconda::gblocks   # Selection of conserved blocks from multiple alignments for their use in phylogenetic analysis.
  - bioconda::blast     # similarity searches bewteen sequences
  - bioconda::emboss    # classical sequence analysis tools, used here for sequence shuffling
  - bioconda::cd-hit    # to generate non-redundant protein sequence sets
  - bioconda::phyml     # maximum likelo-ihood-based phylogenetic inference
  - bioconda::iqtree    # phylogeny by mmaximum-likelihood approach
  - bioconda::figtree   # a graphical viewer of phylogenetic trees and as a program for producing publication-ready figures.
  - bioconda::jalview   # a free program for multiple sequence alignment editing, visualisation and analysis

  ## R dependencies
  - r-base

  ## R packages
  - r::r-knitr # General-purpose tool for dynamic report generation in R using Literate Programming techniques.
  - r::r-ape # Functions for reading, writing, plotting, and manipulating phylogenetic trees ...
  - bioconda::r-phytools # Phylogenetic tools for comparative biology
  - bioconda::bioconductor-biostrings # Efficient manipulation of biological strings
  - bioconda::bioconductor-decipher  # for translation-based alignments of nucleic sequences
  
  ## Python
  - python
  - conda-forge::pandas
