################################################################
## Conda environment for analysis of SARS-CoV-2 sequences
name: covid-19

channels:
  - bioconda
  - conda-forge
  - r

dependencies:

  ## Tools
  - bioconda::muscle    # iterative multiple sequence alignment
  - bioconda::clustalw  # progressive multiple sequence alignment
  - bioconda::gblocks   # to clean multiple alignments - suppress gap positions - before phylogeny inference
  - bioconda::blast     # similarity searches bewteen sequences
  - bioconda::emboss    # classical sequence analysis tools, used here for sequence shuffling
  - bioconda::cd-hit    # to generate non-redundant protein sequence sets
  - bioconda::phyml     # maximum likelo-ihood-based phylogenetic inference
  - bioconda::figtree   # a graphical viewer of phylogenetic trees and as a program for producing publication-ready figures.
  - bioconda::jalview   # a free program for multiple sequence alignment editing, visualisation and analysis
  - tpeulen::pymol-open-source  # structure analysis and visualisation. Note: does not work on Mac OS X

  ## R dependencies
  - r-base

  ## R packages
  - bioconda::bioconductor-biostrings

  ## Python
  - python
  - conda-forge::pandas
